[project]
name = "webdock"
version = "1.0.3"
description = "A type-safe Python wrapper for the Webdock.io API."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "load-dotenv>=0.1.0",
    "requests>=2.31.0,<3",
    "setuptools>=80.9.0",
]
